### ISSUE TITLE
Instructions for HTTPS

### ISSUE THREAD

**Issue by k3tan172** [japharl/serveo_local#2]
When you get some time, could you please provide instructions for HTTPS configuration. It would be much appreciated.

**Comment by japharl** [comment]
Ack, will look into using acme server for let's encrypt certificates at some point and adding those instructions.

**Comment by japharl** [comment]
I spent some time on it this weekend...  I'm hesitant to do this because of the non-trivial complexity dealing with let's encrypt.  In particular, you must use a provider specific (eg. google domains, aws, or similar) api to enable wild card certificates for a domain, without doing manual authentication.  If this is going to be a good reference for serveo, I don't want to have steps that say "go to this point, stop, use this completely different non-trivial tutorial, and come back to this step"...  LMK.

**Comment by k3tan172** [comment]
Could you suggest a common/popular way forward? Just pick one - maybe Google Domains and add the instructions for that? I really would like to get HTTPS going.

**Comment by japharl** [comment]
Ok... As I use Google domains I will do that...

**Comment by japharl** [comment]
Made some progress, slowly.  Google domains isn't easy to work with.  Attempting to use digital ocean for the dns stuff.  I'll update when I make further progress.  Ran into a catch 22, which I think is related to the multiple attempts to get cert bot to work correctly.

**Comment by japharl** [comment]
Ran into catch 22 again.  certbot requires a different module library version than the plugin dns-digitalocean does.  I'll revisit in *2* weeks or so.

**Comment by japharl** [comment]
Ran into a different catch 22...
I ended up giving up on certbot. It doesn't see to work correctly with digital ocean.
I tried acme.sh .  This allows for the certificate to be correctly issued.  However, unfortunately, I'm not sure what of the certificates that were generated as to what the correct parameters are for the serveo client.  Once serveo.com comes back up, I'll ask the mailing list, but not before.

**Comment by japharl** [comment]
No joy... it's like serveo isn't recognizing the option for the cert directory...   If it's not doing that, I'm not sure what I can do...

**Comment by k3tan172** [comment]
It's all good, thanks for your efforts. I have a way of getting HTTPS through Cloudflare's free service, so I'll continue using that.
Thanks!

**Comment by japharl** [comment]
Sounds good, thank you! If I ever pick this up again I'll let you know.

**Comment by japharl** [comment]
@japharl

Zachary Zebrowski
9302 west St,
Manassas, VA 20110

Woot!

Zak
